# Generated by Django 2.0.7 on 2019-04-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProducto', models.TextField()),
                ('nombreProducto', models.TextField()),
                ('precio', models.TextField()),
                ('existencias', models.TextField()),
                ('ubicacion', models.TextField()),
            ],
        ),
    ]
