# Generated by Django 2.0.7 on 2019-04-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo_Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProducto', models.TextField()),
                ('nombreProducto', models.TextField()),
                ('costo', models.TextField(default='0')),
                ('precio', models.TextField(default='0')),
                ('existencias', models.TextField(default='0')),
                ('ubicacion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='costo',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='existencias',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precio',
            field=models.TextField(default='0'),
        ),
    ]
