# Generated by Django 2.0.7 on 2019-04-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20190419_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='articulo_venta',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='articulo_venta',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
