# Generated by Django 2.0.7 on 2019-04-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20190419_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='existencias',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='articulo_venta',
            name='existencias',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
